import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        border: 'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        accent: 'var(--color-accent)',
        'accent-light': 'var(--color-accent-light)',
        success: 'var(--color-success)',
        'success-bg': 'var(--color-success-bg)',
        warning: 'var(--color-warning)',
        'warning-bg': 'var(--color-warning-bg)',
        error: 'var(--color-error)',
        'error-bg': 'var(--color-error-bg)',
        info: 'var(--color-info)',
        'info-bg': 'var(--color-info-bg)',
        malignant: 'var(--color-malignant)',
        'malignant-bg': 'var(--color-malignant-bg)',
        benign: 'var(--color-benign)',
        'benign-bg': 'var(--color-benign-bg)',
        suspicious: 'var(--color-suspicious)',
        'suspicious-bg': 'var(--color-suspicious-bg)',
        'status-pending': 'var(--color-status-pending)',
        'status-pending-bg': 'var(--color-status-pending-bg)',
        'status-processing': 'var(--color-status-processing)',
        'status-processing-bg': 'var(--color-status-processing-bg)',
        'status-ai-complete': 'var(--color-status-ai-complete)',
        'status-ai-complete-bg': 'var(--color-status-ai-complete-bg)',
        'status-reviewed': 'var(--color-status-reviewed)',
        'status-reviewed-bg': 'var(--color-status-reviewed-bg)',
        'status-reported': 'var(--color-status-reported)',
        'status-reported-bg': 'var(--color-status-reported-bg)',
        'status-archived': 'var(--color-status-archived)',
        'status-archived-bg': 'var(--color-status-archived-bg)',
        'priority-routine': 'var(--color-priority-routine)',
        'priority-low': 'var(--color-priority-low)',
        'priority-high': 'var(--color-priority-high)',
        'priority-urgent': 'var(--color-priority-urgent)',
        'role-admin': 'var(--color-role-admin)',
        'role-doctor': 'var(--color-role-doctor)',
        'role-radiologist': 'var(--color-role-radiologist)',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '48px',
      },
      borderRadius: {
        sm: '6px',
        md: '10px',
        lg: '14px',
        xl: '20px',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 1px 3px rgba(15, 23, 42, 0.08)',
        md: '0 4px 12px rgba(15, 23, 42, 0.10)',
        lg: '0 8px 24px rgba(15, 23, 42, 0.12)',
        xl: '0 16px 48px rgba(15, 23, 42, 0.16)',
      },
      fontSize: {
        display: ['32px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        h1: ['24px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        h2: ['20px', { lineHeight: '1.2', fontWeight: '700' }],
        h3: ['16px', { lineHeight: '1.25', fontWeight: '600' }],
        h4: ['14px', { lineHeight: '1.25', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        small: ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.08em', textTransform: 'uppercase' }],
        code: ['13px', { lineHeight: '1.4', fontFamily: '"JetBrains Mono", monospace' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
