"""
In-process smoke test for the inference service. Uses FastAPI's TestClient
so no real server/port is needed. Generates a synthetic grayscale image,
hits /health and /predict (with and without a manual ROI), and asserts the
response shape matches the documented API contract.
"""
import os
import sys
import io

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# Use whatever MODEL_BUNDLE_PATH / INFERENCE_DEVICE the caller already set
# (e.g. to point at a real trained bundle). Falls back to the dummy bundle
# generated by make_dummy_bundle.py, used only to verify the serving code.
os.environ.setdefault("MODEL_BUNDLE_PATH", os.path.join(os.path.dirname(__file__), "dummy_bundle.pth"))
os.environ.setdefault("INFERENCE_DEVICE", "cpu")

import numpy as np
from PIL import Image
from fastapi.testclient import TestClient

from app.main import app

with TestClient(app) as client:

    print("=== /health ===")
    r = client.get("/health")
    print(r.status_code, r.json())
    assert r.status_code == 200, "health check failed"
    assert r.json()["status"] == "ok"
    assert r.json()["label_names"] == ["Benign", "Malignant"]

    # Synthetic 1024x768 grayscale "mammogram"
    rng = np.random.default_rng(0)
    synthetic = (rng.random((1024, 768)) * 255).astype(np.uint8)
    buf = io.BytesIO()
    Image.fromarray(synthetic, mode="L").save(buf, format="PNG")
    image_bytes = buf.getvalue()

    print("\n=== /predict (no ROI -> segmentation-first localization) ===")
    r = client.post("/predict", files={"image": ("synthetic.png", image_bytes, "image/png")})
    print(r.status_code)
    data = r.json()
    assert r.status_code == 200, f"predict failed: {data}"
    assert data["roi_source"] in ("segmentation_predicted_mask", "center_crop_fallback")
    assert data["prediction"] in ("Benign", "Malignant")
    assert 0.0 <= data["confidence"] <= 1.0
    assert set(data["probabilities"].keys()) == {"Benign", "Malignant"}
    assert len(data["heatmap_png_base64"]) > 100
    assert len(data["segmentation_mask_png_base64"]) > 100
    assert data["pipeline_version"] == "medguard-seg-first-v1"
    assert isinstance(data["processing_ms"], int)
    print("prediction:", data["prediction"], "| confidence:", data["confidence"])
    print("probabilities:", data["probabilities"])
    print("roi_source:", data["roi_source"], "| processing_ms:", data["processing_ms"])

    print("\n=== /predict (with manual ROI -> manual_roi) ===")
    r = client.post(
        "/predict",
        files={"image": ("synthetic.png", image_bytes, "image/png")},
        data={"roi_x": 100, "roi_y": 80, "roi_w": 300, "roi_h": 250},
    )
    data = r.json()
    assert r.status_code == 200, f"predict with ROI failed: {data}"
    assert data["roi_source"] == "manual_roi"
    print("prediction:", data["prediction"], "| roi_source:", data["roi_source"])

    print("\n=== /predict (partial ROI -> should 400) ===")
    r = client.post(
        "/predict",
        files={"image": ("synthetic.png", image_bytes, "image/png")},
        data={"roi_x": 100, "roi_y": 80},  # missing roi_w, roi_h
    )
    print(r.status_code, r.json())
    assert r.status_code == 400

    print("\nALL SMOKE TESTS PASSED")
